[package]
name = "hex_play"
version = "0.1.0"
authors = ["Alex Berry <highwaybobbery@gmail.com>"]

[dependencies]
piston = "0.22.1"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.26.1"
piston2d-opengl_graphics = "0.29.0"
vecmath = "*"
